export { default as Product } from "./Product";
export { default as Selector } from "./Selector";
export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Blog } from "./Blog";
export { default as Privacy } from "./Privacy";
export { default as Terms } from "./Terms";
export { default as Imprint } from "./Imprint";
export { default as Howto } from "./Howto";
